# Generated by Django 4.1 on 2022-12-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0002_productviewcardmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(db_index=True, max_length=20, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, verbose_name='Содержание')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
            },
        ),
        migrations.AddField(
            model_name='productmodel',
            name='summary',
            field=models.TextField(blank=True, verbose_name='Краткое описание'),
        ),
        migrations.DeleteModel(
            name='ProductViewCardModel',
        ),
    ]
