# Generated by Django 4.1 on 2022-12-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0003_aboutmodel_productmodel_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutmodel',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/about/', verbose_name='Изображение'),
        ),
    ]
