# Generated by Django 4.1 on 2022-12-20 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0004_aboutmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='specific',
            field=models.CharField(blank=True, max_length=200, verbose_name='Характеристики'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='size',
            field=models.CharField(blank=True, choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=2, verbose_name='Размер'),
        ),
    ]
