# Generated by Django 4.1 on 2022-12-20 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0006_alter_productmodel_colour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='specific',
            field=models.TextField(blank=True, max_length=200, verbose_name='Характеристики'),
        ),
    ]
